/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */
export type URL = any;
export type Promise = any;
export function prefetch(urls: URL[]): any {}
export async function clearMemoryCache(): Promise<boolean> {
  return false;
}
export async function clearDiskCache(promise: Promise): Promise<any> {}
