/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type VideoPlayer = any;

export type VideoContentFit = any;

export type CGVector = any;

export type ViewProps = {
  player: VideoPlayer | undefined;
  nativeControls: boolean | undefined;
  contentFit: VideoContentFit | undefined;
  contentPosition: CGVector | undefined;
  allowsFullscreen: boolean | undefined;
  showsTimecodes: boolean | undefined;
  requiresLinearPlayback: boolean | undefined;
};

export function View(props: ViewProps) {}

export class VideoPlayer {}
